apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: lua-filter
  namespace: istio-system
spec:
  workloadSelector:
    labels:
      istio: ingressgateway
  configPatches:
  - applyTo: HTTP_FILTER
    match:
      context: GATEWAY
      listener:
        filterChain:
          filter:
            name: "envoy.http_connection_manager"
            subFilter:
              name: "envoy.router"
    patch:
      operation: INSERT_BEFORE
      value:
       name: envoy.lua
       typed_config:
         "@type": "type.googleapis.com/envoy.extensions.filters.http.lua.v3.Lua"
         inlineCode: |
            function envoy_on_request(request_handle)
                local h = "Hello"
                local w = "World"
                print(h..w)

                local body = request_handle:body()
                result = tostring(body)
                -- request_handle:logDebug(result)                
                request_handle:headers():add("authorization", "it works!")
                request_handle:logWarn(" ========= Hola ========== ")
            end
            function envoy_on_response(response_handle)
                  filter_name = "ENVOY"
                  response_handle:headers():add("my_Filter", filter_name)
                  response_handle:logWarn(" ========= XXXXX ========== ")
            end